export const categories = ["A", "B", "C", "D", "E"]

export const questions = [
  { id: 1, category: "A", text: "このチームでは私の失敗が非難されがちだ", value: 1 },
  { id: 2, category: "A", text: "このチームでは私は言いたいことを我慢している", value: 1 },
  { id: 3, category: "A", text: "このチームでは自分の居場所がなく感じることがある", value: 1 },
  { id: 4, category: "A", text: "このチームでは私の個性が尊重されている", value: 1 },
  { id: 5, category: "A", text: "このチームでは私は周囲にも言いたいことを言わせている", value: 1 },
  { id: 6, category: "A", text: "このチームでは私はＨＥＬＰを出しにくい", value: 1 },
  { id: 7, category: "A", text: "このチームでは私は適度に挨拶をしている", value: 1 },
  { id: 8, category: "B", text: "私は自分の仕事に対する原動力が明らかになっている", value: 1 },
  { id: 9, category: "B", text: "私が自分が仕事において何を価値観として大事にしたいかが明らかになっている", value: 1 },
  { id: 10, category: "B", text: "私は自分のキャリアビジョンが描けている（短期的でもよい）", value: 1 },
  { id: 11, category: "C", text: "私はこの会社の理念やビジョンを理解している", value: 1 },
  { id: 12, category: "C", text: "私はこの会社の理念やビジョンに共感している", value: 1 },
  { id: 13, category: "C", text: "私はこの会社の理念やビジョンにを常に念頭に置いて行動している", value: 1 },
  { id: 14, category: "D", text: "私はこの会社の理念やビジョンを考えるとやる気が出てくる", value: 1 },
  { id: 15, category: "D", text: "私は自分がやりたいことがこの会社で実現できるという実感がある", value: 1 },
  { id: 16, category: "D", text: "この会社では自分が適切に評価されていると感じる", value: 1 },
  { id: 17, category: "D", text: "上司は自分のキャリアビジョンを理解している", value: 1 },
  { id: 18, category: "D", text: "上司は私のキャリアビジョンを応援してくれている", value: 1 },
  { id: 19, category: "D", text: "このチームでは、会社の理念やビジョンに紐づいたチームのビジョンがある", value: 1 },
  { id: 20, category: "D", text: "このチームのビジョンを踏まえて、自分がどんな役割なのかが明らかになっている", value: 1 },
]

export const questionsForOthers = [
  { id: 1, category: "A", text: "このチームでは対象者は本人の失敗が非難されがちだと感じている", value: 1 },
  { id: 2, category: "A", text: "このチームでは対象者は言いたいことを我慢している", value: 1 },
  { id: 3, category: "A", text: "このチームでは対象者は本人の居場所がなく感じることがある", value: 1 },
  { id: 4, category: "A", text: "このチームでは対象者は本人の個性が尊重されている実感がある", value: 1 },
  { id: 5, category: "A", text: "このチームでは対象者は周囲にも言いたいことを言わせている", value: 1 },
  { id: 6, category: "A", text: "このチームでは対象者はＨＥＬＰを出しにくそうにしている", value: 1 },
  { id: 7, category: "A", text: "このチームでは対象者は適度に挨拶をしている", value: 1 },
  { id: 8, category: "B", text: "対象者は本人の仕事に対する原動力が明らかになっている", value: 1 },
  { id: 9, category: "B", text: "対象者は本人が仕事において何を価値観として大事にしたいかが明らかになっている", value: 1 },
  { id: 10, category: "B", text: "対象者は本人のキャリアビジョンが描けている（短期的でもよい）", value: 1 },
  { id: 11, category: "C", text: "対象者はこの会社の理念やビジョンを理解している", value: 1 },
  { id: 12, category: "C", text: "対象者はこの会社の理念やビジョンに共感している", value: 1 },
  { id: 13, category: "C", text: "対象者はこの会社の理念やビジョンにを常に念頭に置いて行動している", value: 1 },
  { id: 14, category: "D", text: "対象者はこの会社の理念やビジョンを考えるとやる気が出てくる", value: 1 },
  { id: 15, category: "D", text: "対象者は本人がやりたいことがこの会社で実現できるという実感がある", value: 1 },
  { id: 16, category: "D", text: "対象者はこの会社では本人が適切に評価されていると感じている", value: 1 },
  { id: 17, category: "D", text: "対象者は本人の上司が本人のキャリアビジョンを理解してくれている実感がある", value: 1 },
  { id: 18, category: "D", text: "対象者は本人の上司が本人のキャリアビジョンを応援してくれている実感がある", value: 1 },
  { id: 19, category: "D", text: "対象者はこのチームでは、会社の理念やビジョンに紐づいたチームのビジョンがあると実感している", value: 1 },
  { id: 20, category: "D", text: "対象者はこのチームのビジョンを踏まえて、本人がどんな役割なのかが明らかになっている", value: 1 },
  { id: 21, category: "D", text: "対象者は上司と定期的に面談をしている", value: 1 },
  { id: 22, category: "D", text: "私はこの会社で行っている業務がしっくりきている", value: 1 },
  { id: 23, category: "E", text: "対象者はこの会社で意欲的に働けている", value: 1 },
]